insert into public.preset_images (category, label, storage_path) values
('Entradas', 'Rissois', 'entradas/rissois.jpg'),
('Entradas', 'Salada Mista', 'entradas/salada-mista.jpg'),
('Entradas', 'Samosas', 'entradas/samosas.jpg'),
('Entradas', 'Sopa Carne Legumes', 'entradas/sopa-carne-legumes.jpg'),
('Pratos Principais', 'Arroz Branco', 'pratos-principais/arroz-branco.jpg'),
('Pratos Principais', 'Batata Frita', 'pratos-principais/batata-frita.jpg'),
('Pratos Principais', 'Bife Arroz Salada', 'pratos-principais/bife-arroz-salada.jpg'),
('Pratos Principais', 'Bife Fritas', 'pratos-principais/bife-fritas.jpg'),
('Pratos Principais', 'Cachorro Quente', 'pratos-principais/cachorro-quente.jpg'),
('Pratos Principais', 'Camarao Ao Molho', 'pratos-principais/camarao-ao-molho.jpg'),
('Pratos Principais', 'Camarao Grelhado', 'pratos-principais/camarao-grelhado.jpg'),
('Pratos Principais', 'Frango A Mocambicana', 'pratos-principais/frango-a-mocambicana.jpg'),
('Pratos Principais', 'Frango A Zambeziana', 'pratos-principais/frango-a-zambeziana.jpg'),
('Pratos Principais', 'Frango Assado Inteiro', 'pratos-principais/frango-assado-inteiro.jpg'),
('Pratos Principais', 'Frango Camarao Arroz', 'pratos-principais/frango-camarao-arroz.jpg'),
('Pratos Principais', 'Frango Esparguete Fritas', 'pratos-principais/frango-esparguete-fritas.jpg'),
('Pratos Principais', 'Frango Frito', 'pratos-principais/frango-frito.jpg'),
('Pratos Principais', 'Frango Grelhado Arroz Salada', 'pratos-principais/frango-grelhado-arroz-salada.jpg'),
('Pratos Principais', 'Frango Grelhado Fritas', 'pratos-principais/frango-grelhado-fritas.jpg'),
('Pratos Principais', 'Hamburguer', 'pratos-principais/hamburguer.jpg'),
('Pratos Principais', 'Peixe Ao Molho', 'pratos-principais/peixe-ao-molho.jpg'),
('Pratos Principais', 'Peixe Frito Fritas', 'pratos-principais/peixe-frito-fritas.jpg'),
('Pratos Principais', 'Peixe Grelhado Salada', 'pratos-principais/peixe-grelhado-salada.jpg'),
('Pratos Principais', 'Sanduiche Fiambre Queijo', 'pratos-principais/sanduiche-fiambre-queijo.jpg'),
('Bebidas', '2m Garrafa', 'bebidas/2m-garrafa.jpg'),
('Bebidas', '2m Lata', 'bebidas/2m-lata.jpg'),
('Bebidas', 'Agua Vumba', 'bebidas/agua-vumba.jpg'),
('Bebidas', 'Brutal Fruit Spritzer', 'bebidas/brutal-fruit-spritzer.jpg'),
('Bebidas', 'Castle Lite', 'bebidas/castle-lite.jpg'),
('Bebidas', 'Cerveja Garrafa', 'bebidas/cerveja-garrafa.jpg'),
('Bebidas', 'Coca Cola', 'bebidas/coca-cola.jpg'),
('Bebidas', 'Compal Sumos', 'bebidas/compal-sumos.jpg'),
('Bebidas', 'Fanta Laranja', 'bebidas/fanta-laranja.jpg'),
('Bebidas', 'Fanta Morango', 'bebidas/fanta-morango.jpg'),
('Bebidas', 'Fanta Uva', 'bebidas/fanta-uva.jpg'),
('Bebidas', 'Gordons Gin', 'bebidas/gordons-gin.jpg'),
('Bebidas', 'Heineken', 'bebidas/heineken.jpg'),
('Bebidas', 'Impala Milho Suave', 'bebidas/impala-milho-suave.jpg'),
('Bebidas', 'Jack Daniels Honey', 'bebidas/jack-daniels-honey.jpg'),
('Bebidas', 'Laurentina Preta', 'bebidas/laurentina-preta.jpg'),
('Bebidas', 'Red Bull', 'bebidas/red-bull.jpg'),
('Bebidas', 'Santal Nectar', 'bebidas/santal-nectar.jpg'),
('Bebidas', 'Savanna Dry', 'bebidas/savanna-dry.jpg'),
('Bebidas', 'Schweppes Gengibre', 'bebidas/schweppes-gengibre.jpg'),
('Bebidas', 'Schweppes Limao', 'bebidas/schweppes-limao.jpg'),
('Bebidas', 'Sprite', 'bebidas/sprite.jpg'),
('Bebidas', 'Vinho Tinto', 'bebidas/vinho-tinto.jpg'),
('Sobremesas', 'Bolo Amarelo', 'sobremesas/bolo-amarelo.jpg'),
('Sobremesas', 'Bolo Chocolate', 'sobremesas/bolo-chocolate.jpg'),
('Sobremesas', 'Frutas Variadas', 'sobremesas/frutas-variadas.jpg'),
('Sobremesas', 'Gelado 3 Sabores', 'sobremesas/gelado-3-sabores.jpg'),
('Sobremesas', 'Mousse Chocolate', 'sobremesas/mousse-chocolate.jpg'),
('Sobremesas', 'Pudim', 'sobremesas/pudim.jpg'),
('Sobremesas', 'Salada Frutas', 'sobremesas/salada-frutas.jpg'),
('Sobremesas', 'Sorvete Baunilha', 'sobremesas/sorvete-baunilha.jpg'),
('Sobremesas', 'Sorvete Chocolate', 'sobremesas/sorvete-chocolate.jpg');
